# Generated by Django 5.2.7 on 2025-10-24 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_topic_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
