# Generated by Django 5.2.7 on 2025-10-24 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_board_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='message',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
