# Generated by Django 5.2.7 on 2025-10-25 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_topic_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
