# Generated by Django 5.2.7 on 2025-10-25 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_topic_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='slug',
            new_name='topic_slug',
        ),
    ]
