# Generated by Django 5.2.7 on 2025-10-25 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_rename_slug_topic_topic_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='topic_slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
