# Generated by Django 5.2.7 on 2025-10-25 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0009_topic_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='replies',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
