# Generated by Django 5.2.7 on 2025-10-25 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0010_topic_replies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='replies',
        ),
    ]
